vich_uploader:
    db_driver: orm

    mappings:
        dechet_image:
             uri_prefix: /images/dechets
             upload_destination: '%kernel.project_dir%/public/images/dechets'
             namer: Vich\UploaderBundle\Naming\UniqidNamer
        user_file:
                uri_prefix: /file/client
                upload_destination: '%kernel.project_dir%/public/file/client'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
                inject_on_load: false 
                delete_on_update: true 
                delete_on_remove: true            
 