#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fp_js_form_validator:
    resource: "@FpJsFormValidatorBundle/Resources/config/routing.xml"
    prefix: /fp_js_form_validator