<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Ovd\RecaptchaBundle\Type\RecaptchaSubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrue;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'attr' => ['placeholder' => 'example@example.com']
            ])
            ->add('password', PasswordType::class, [
                'label' => 'Mots de passe (Lettre et chiffre avec symbole)',


            ])
            ->add('FisrtName', TextType::class, [
                'label' => 'Prenom'
            ])
            ->add('LastName', TextType::class, [
                'label' => 'Nom de la famille'
            ])
            ->add('phone', TextType::class, [
                'label' => 'Telephone'
            ])
            ->add('confirmepassword', PasswordType::class, [
                'label' => 'Comfirmation'
            ])
            ->add('indicateur', ChoiceType::class, [
                'choices'  => [
                    'Afghanistan (+93)' =>    +93,
                    'Afrique du Sud (+27)' =>    +27,
                    'Albanie (+355)' =>    +355,
                    'Algérie (+213)' =>    +213,
                    'Allemagne (+49)' =>    +49,
                    'Andorre (+376)' =>    +376,
                    'Angola (+244)' =>    +244,
                    'Anguilla (+1264)' =>    +1264,
                    'Antarctique-Casey (+672)' =>    +672,
                    'Antarctique-Scott (+672)' =>    +672,
                    'Antigua et Barbuda  (+1268)' =>    +1268,
                    'Antigua-et-Barbuda (+268)' =>    +268,
                    'Antilles Françaises (+596)' =>    +596,
                    'Antilles hollandaise (+599)' =>    +599,
                    'Arabie saoudite (+966)' =>    +966,
                    'Argentine (+54)' =>    +54,
                    'Arménie (+374)' =>    +374,
                    'Aruba (+297)' =>    +297,
                    'Ascension (+247)' =>    +247,
                    'Atlantique Est (+871)' =>    +871,
                    'Atlantique Ouest (+874)' =>    +874,
                    'Australie (+61)' =>    +61,
                    'Autriche (+43)' =>    +43,
                    'Azerbaïdjan (+994)' =>    +994,
                    'Bahamas (+1242)' =>    +1242,
                    'Bahreïn (+973)' =>    +973,
                    'Bangladesh (+880)' =>    +880,
                    'Barbade (+1246)' =>    +1246,
                    'Belgique (+32)' =>    +32,
                    'Belize (+501)' =>    +501,
                    'Bermudes (+1441)' =>    +1441,
                    'Bhoutan (+975)' =>    +975,
                    'Biélorussie (+375)' =>    +375,
                    'Bolivie (+591)' =>    +591,
                    'Bosnie-Herzégovine (+387)' =>    +387,
                    'Botswana (+267)' =>    +267,
                    'Brunei Darussalam (+673)' =>    +673,
                    'Brésil (+55)' =>    +55,
                    'Bulgarie (+359)' =>    +359,
                    'Burkina Faso (+226)' =>    +226,
                    'Burundi (+257)' =>    +257,
                    'Bénin (+229)' =>    +229,
                    'Cambodge (+855)' =>    +855,
                    'Cameroun (+237)' =>    +237,
                    'Canada (+1)' =>    +1,
                    'Cap-Vert (+238)' =>    +238,
                    'Cayman (Iles) (+1345)' =>    +1345,
                    'Chili (+56)' =>    +56,
                    'Chine (+86)' =>    +86,
                    'Chypre (+357)' =>    +357,
                    'Colombie (+57)' =>    +57,
                    'Congo (+242)' =>    +242,
                    'Congo Zaïre (Rep. Dem.) (+243)' =>    +243,
                    'Corée du Nord (+850)' =>    +850,
                    'Corée du Sud (+82)' =>    +82,
                    'Costa Rica (+506)' =>    +506,
                    'Croatie (+385)' =>    +385,
                    'Cuba (+53)' =>    +53,
                    'Côte d\'Ivoire (+225)' =>    +225,
                    'Danemark (+45)' =>    +45,
                    'Djibouti (+253)' =>    +253,
                    'Dominicaine (Rep.) (+1809)' =>    +1809,
                    'Dominique (+1767)' =>    +1767,
                    'Egypte (+20)' =>    +20,
                    'Emirats arabes unis (+971)' =>    +971,
                    'Equateur (+593)' =>    +593,
                    'Erythrée (+291)' =>    +291,
                    'Espagne (+349)' =>    +349,
                    'Estonie (+372)' =>    +372,
                    'Etats Unis d\'Amérique (+1)' =>    +1,
                    'Ethiopie (+251)' =>    +251,
                    'Fidji (+679)' =>    +679,
                    'Finlande (+358)' =>    +358,
                    'France (+33)' =>    +33,
                    'Fédération russe (+7)' =>    +7,
                    'Gabon (+241)' =>    +241,
                    'Gambie (+220)' =>    +220,
                    'Ghana (+233)' =>    +233,
                    'Gibraltar (+350)' =>    +350,
                    'Grenade (+1473)' =>    +1473,
                    'Groà«nland (+299)' =>    +299,
                    'Grèce (+30)' =>    +30,
                    'Guadeloupe (+590)' =>    +590,
                    'Guam (+671)' =>    +671,
                    'Guatemala (+502)' =>    +502,
                    'Guinée (+224)' =>    +224,
                    'Guinée Française (+594)' =>    +594,
                    'Guinée équatoriale (+240)' =>    +240,
                    'Guinée-Bissao (+245)' =>    +245,
                    'Guyane (+592)' =>    +592,
                    'Géorgie (+995)' =>    +995,
                    'Hawaï (+1808)' =>    +1808,
                    'Haïti (+509)' =>    +509,
                    'Honduras (+504)' =>    +504,
                    'Hong Kong (+852)' =>    +852,
                    'Hongrie (+36)' =>    +36,
                    'Ile Christmas (+61)' =>    +61,
                    'Ile Feroe (+298)' =>    +298,
                    'Ile de Norfolk (+672)' =>    +672,
                    'Iles Caïmans (+345)' =>    +345,
                    'Iles Cook (+682)' =>    +682,
                    'Iles Falklands (+500)' =>    +500,
                    'Iles Salomon (+677)' =>    +677,
                    'Iles vierges américaines (+340)' =>    +340,
                    'Inde (+91)' =>    +91,
                    'Indonésie (+62)' =>    +62,
                    'Iran (+98)' =>    +98,
                    'Iraq (+964)' =>    +964,
                    'Irlande (+353)' =>    +353,
                    'Islande (+354)' =>    +354,
                    'Israà«l (+972)' =>    +972,
                    'Italie (+390)' =>    +390,
                    'Jamaïque (+1876)' =>    +1876,
                    'Japon (+81)' =>    +81,
                    'Jordanie (+962)' =>    +962,
                    'Kazakhstan (+7)' =>    +7,
                    'Kenya (+254)' =>    +254,
                    'Kirghizistan (+996)' =>    +996,
                    'Kiribati (+686)' =>    +686,
                    'Koweït (+965)' =>    +965,
                    'Laos (+856)' =>    +856,
                    'Lesotho (+266)' =>    +266,
                    'Lettonie (+371)' =>    +371,
                    'Liban (+961)' =>    +961,
                    'Libye (+218)' =>    +218,
                    'Libéria (+231)' =>    +231,
                    'Liechtenstein (+423)' =>    +423,
                    'Lituanie (+370)' =>    +370,
                    'Luxembourg (+352)' =>    +352,
                    'Macao (+853)' =>    +853,
                    'Macédoine (+389)' =>    +389,
                    'Madagascar (+261)' =>    +261,
                    'Malaisie (+60)' =>    +60,
                    'Malawi (+265)' =>    +265,
                    'Maldives (+960)' =>    +960,
                    'Mali (+223)' =>    +223,
                    'Malte (+356)' =>    +356,
                    'Marisat (Atlantique Est) (+872)' =>    +872,
                    'Marisat (Atlantique Ouest) (+873)' =>    +873,
                    'Maroc (+212)' =>    +212,
                    'Marshall (+692)' =>    +692,
                    'Maurice (+230)' =>    +230,
                    'Mauritanie (+222)' =>    +222,
                    'Mayotte (+269)' =>    +269,
                    'Mexique Centre (+52)' =>    +52,
                    'Micronésie (+691)' =>    +691,
                    'Moldavie (+373)' =>    +373,
                    'Monaco (+377)' =>    +377,
                    'Mongolie (+976)' =>    +976,
                    'Monteserrat (+664)' =>    +664,
                    'Montserrat (+1664)' =>    +1664,
                    'Mozambique (+258)' =>    +258,
                    'Namibie (+264)' =>    +264,
                    'Nauru (+674)' =>    +674,
                    'Nicaragua (+505)' =>    +505,
                    'Niger (+227)' =>    +227,
                    'Nigeria (+234)' =>    +234,
                    'Niue (+683)' =>    +683,
                    'Norfolk (Ile) (+6723)' =>    +6723,
                    'Norvège (+47)' =>    +47,
                    'Nouvelle-Calédonie (+687)' =>    +687,
                    'Nouvelle-Zélande (+64)' =>    +64,
                    'Népal (+977)' =>    +977,
                    'Oman (+968)' =>    +968,
                    'Ouganda (+256)' =>    +256,
                    'Ouzbekistan (+7)' =>    +7,
                    'Pakistan (+92)' =>    +92,
                    'Palau (+680)' =>    +680,
                    'Palestine (+970)' =>    +970,
                    'Panama (+507)' =>    +507,
                    'Papouasie - Nouvelle Guinée (+675)' =>    +675,
                    'Paraguay (+595)' =>    +595,
                    'Pays-Bas  (+31)' =>    +31,
                    'Philippines (+63)' =>    +63,
                    'Pologne (+48)' =>    +48,
                    'Polynésie Française (+689)' =>    +689,
                    'Porto Rico (+1787)' =>    +1787,
                    'Portugal (+351)' =>    +351,
                    'Pérou (+51)' =>    +51,
                    'Qatar (+974)' =>    +974,
                    'Roumanie (+40)' =>    +40,
                    'Royaume-Uni (+44)' =>    +44,
                    'Rwanda (+250)' =>    +250,
                    'République Centrafricaine (+236)' =>    +236,
                    'République Dominicaine (+809)' =>    +809,
                    'République Tchèque (+420)' =>    +420,
                    'République comorienne (+269)' =>    +269,
                    'République du Tchad (+235)' =>    +235,
                    'Réunion (+262)' =>    +262,
                    'Saint Eustache (+599)' =>    +599,
                    'Saint Hélène (+290)' =>    +290,
                    'Saint Martin (+599)' =>    +599,
                    'Saint-Christophe-et-Niévès (+869)' =>    +869,
                    'Saint-Kitts-et-Nevis (+1869)' =>    +1869,
                    'Saint-Marin (+378)' =>    +378,
                    'Saint-Vincent-et-Grenadines (+1809)' =>    +1809,
                    'Saint-Vincent-et-les Grenadines (+809)' =>    +809,
                    'Sainte-Lucie (+1758)' =>    +1758,
                    'Saipan (+670)' =>    +670,
                    'Salvador (+503)' =>    +503,
                    'Samoa Américaines (+684)' =>    +684,
                    'Samoa occidentales (+685)' =>    +685,
                    'Sao Tomé-et-Principe (+239)' =>    +239,
                    'Seychelles (+248)' =>    +248,
                    'Sierra Leone (+232)' =>    +232,
                    'Singapour (+65)' =>    +65,
                    'Slovaquie (+421)' =>    +421,
                    'Slovénie (+386)' =>    +386,
                    'Somalie (+252)' =>    +252,
                    'Soudan (+249)' =>    +249,
                    'Sri Lanka (+94)' =>    +94,
                    'Suisse (+41)' =>    +41,
                    'Suriname (+597)' =>    +597,
                    'Suède (+46)' =>    +46,
                    'Swaziland (+268)' =>    +268,
                    'Syrie (+963)' =>    +963,
                    'Sénégal (+221)' =>    +221,
                    'Tadjikistan (Rep. du) (+992)' =>    +992,
                    'Taiwan (+886)' =>    +886,
                    'Tanzanie (+255)' =>    +255,
                    'Thaïlande (+66)' =>    +66,
                    'Togo (+228)' =>    +228,
                    'Tokelau (+690)' =>    +690,
                    'Tonga (+676)' =>    +676,
                    'Trinité-et-Tobago (+1868)' =>    +1868,
                    'Tunisie (+216)' =>    +216,
                    'Turkménistan (+993)' =>    +993,
                    'Turks et Caïcos (Iles) (+1649)' =>    +1649,
                    'Turks et caicos (+649)' =>    +649,
                    'Turquie (+90)' =>    +90,
                    'Tuvalu (+688)' =>    +688,
                    'Ukraine (+380)' =>    +380,
                    'Union Birmane (+95)' =>    +95,
                    'Uruguay (+598)' =>    +598,
                    'Vanuatu (+678)' =>    +678,
                    'Vatican (+39)' =>    +39,
                    'Vierges Américaines (Iles) (+1340)' =>    +1340,
                    'Vierges Britanniques (Iles) (+1284)' =>    +1284,
                    'Viêt-Nam (+84)' =>    +84,
                    'Vénézuela (+58)' =>    +58,
                    'Wallis et Futuna (+681)' =>    +681,
                    'Yougoslavie (+381)' =>    +381,
                    'Yémen (+967)' =>    +967,
                    'Zambie (+260)' =>    +260,
                    'Zimbabwe (+263)' =>    +263,

                ],

            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'inherit_data' => true,

        ]);
    }
}